name: Docker

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/yolo
          tags: latest
          dockerfile: Dockerfile
          cache_froms: cyndie7216/yolo
